# Generated by Django 4.2.7 on 2026-09-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Milk & Dairy', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('unit', models.CharField(default='1 Litre Pouch', max_length=100)),
                ('rating', models.FloatField(default=4.8)),
                ('reviews_count', models.IntegerField(default=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.URLField(default='https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop&q=80')),
                ('stock', models.IntegerField(default=50)),
                ('fat_content', models.CharField(blank=True, max_length=50, null=True)),
                ('shelf_life', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
