# Generated by Django 4.2.7 on 2026-09-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Rahul Sharma', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(default='Morning (6:00 AM - 7:00 AM)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Out for Delivery', max_length=50),
        ),
    ]
